- name: Create repository for Elasticsearch
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Copy default configuration for Elasticsearch
  copy:
    src: etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    dest: /etc/elasticsearch/

- name: Copy JVM options for Elasticsearch
  copy:
    src: etc/elasticsearch/jvm.options
    owner: elasticsearch
    group: elasticsearch
    dest: /etc/elasticsearch/

- name: Update /etc/security/limits.conf for Elasticsearch
  pam_limits:
    domain: elasticsearch
    limit_type: '-'
    limit_item: nofile
    value: 65536

- name: Update sysctl.conf for Elasticsearch
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
    reload: yes
  when: not ci

- name: Start and enable Elasticsearch (at boot time)
  service:
    name: elasticsearch
    enabled: yes
    state: started
