- name: Create the repository for postgres
  copy:
    src: postgres.repo
    dest: /etc/yum.repos.d/postgres.repo

- name: Install PostgreSQL
  yum:
    state: present
    name:
      - postgresql11-server
      - python-psycopg2

- name: Initialize database
  command: service postgresql-11 initdb

- name: Copy pg_hba.conf configuration
  copy:
    src: pg_hba.conf
    owner: postgres
    group: postgres
    dest: /var/lib/pgsql/11/data/pg_hba.conf

- name: Copy pg_hba.conf configuration
  copy:
    src: postgresql.conf
    owner: postgres
    group: postgres
    dest: /var/lib/pgsql/11/data/postgresql.conf

- name: Start and enable Postgres (at boot time)
  service:
    name: postgresql-11
    state: started
    enabled: yes

- name: Create 'molgenis'-user for PostgreSQL
  become: true
  become_user: postgres
  postgresql_user:
    name: molgenis
    password: molgenis
    encrypted: True

- name: Create database 'molgenis' as PostgreSQL
  become: true
  become_user: postgres
  postgresql_db:
    name: molgenis
    owner: molgenis
    encoding: UTF8
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'

- name: Create 'molgenis'-scheme with PSQL
  become: true
  become_user: postgres
  command: psql -c 'CREATE SCHEMA IF NOT EXISTS molgenis;'

- name: Grant rights to 'molgenis'-user on 'molgenis'-scheme with PSQL
  become: true
  become_user: postgres
  command: psql -c 'GRANT ALL PRIVILEGES ON SCHEMA molgenis TO molgenis;'
